# Generated by Django 3.2.11 on 2023-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230422_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
