# Generated by Django 3.2.11 on 2023-04-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
