# Generated by Django 3.2.11 on 2023-05-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230504_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
