# Generated by Django 3.2.11 on 2023-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='file_slip',
            field=models.FileField(upload_to='slip/'),
        ),
    ]
